introductions/1.02.prepare-for-development.md

fix image layout

---

_layouts/default.html

Reverts mixi-inc/AndroidTraining#52

Revert "fix analytics code"

---

_layouts/default.html

Reverts mixi-inc/AndroidTraining#53

Revert "Revert "fix analytics code""

---

fundamentals/2.01.create-layout.md

* どのプロジェクトを開けば良いかを明記しました。
* ページ内リンクが機能していなかったので、アンカーを追加しました

プロジェクトで作業するための手順の説明を追加

---

fundamentals/2.01.create-layout.md

第1回 Android Trainingに参加したものです。
一点typoっぽいものを見つけました。
初めてのプルリクなので、至らないところあったらすみません。

create-layout fix typo

---

fundamentals/2.02.activity-and-fragment.md

add project path

---

fundamentals/2.03.application-resource-management.md

プロジェクトのパスが間違っていたようでしたので修正しました。

第3回実習問題中のパスを修正

---

.gitignore
Gemfile
_config.yml
_layouts/default.html

Support viewport

---

.gitignore
Gemfile
_config.yml
_includes/footer.html
_includes/header.html
_layouts/default.html
index.md
stylesheets/main.css

Add schema org

---

stylesheets/main.css

- 大きい画像の場合に幅に合わせたサイズで表示されるように修正

fix image size

---

stylesheets/main.css

- コードの幅がはみ出した時にはみ出した部分が表示されない問題を修正

fix style of overflow at highlight

---

AndroidStudio/answers/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/BindableAdapter.java
AndroidStudio/answers/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/ClickableAdapter.java
AndroidStudio/answers/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/MainActivity.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/BindableAdapter.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/ClickableAdapter.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/MainActivity.java

ViewHolderパターンを使うように修正

---

README.md

READMEに文言追記

---

introductions/1.05.how-to-build-for-gradle.md

[Android のビルドについて(Gradle)](http://mixi-inc.github.io/AndroidTraining/introductions/1.05.how-to-build-for-gradle.html)を参考に写経していたところ、エラーに遭遇したので修正しました。

「繰り返し」のサンプルコードがエラーになるのを修正

---

README.md

Remove link to gitter

---

fundamentals/2.02.activity-and-fragment.md
fundamentals/2.03.application-resource-management.md
fundamentals/2.04.messaging-and-notification.md
fundamentals/2.05.actionbar-and-interaction-control.md
fundamentals/2.06.listView-and-viewPager.md
fundamentals/2.10.database.md
fundamentals/2.11.testing.md
introductions/1.04.basic-knowledge.md

fix layout of web page

---

README.md

elicpseの説明を削除

---

fundamentals/2.04.messaging-and-notification.md

Remove DT tag which is not used.

---

fundamentals/2.04.messaging-and-notification.md

Add description for 2.04.messaging and notification

---

docs/introductions/1.01.about-android-os.md

Update API version and code name of Android 8.0.
Additionally, put `MR1`, `MR2` to some versions according to `Build.VERSION_CODES`.

Update code names

---

AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/AnimationPracticeActivity.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/ClickableAdapter.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/DrawablePracticeActivity.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/MainActivity.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/StringPractice1And2Activity.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/StringPractice3Activity.java

ActionBarActivityがdeprecatedなのでAppCompatActivityにreplace

---

docs/fundamentals/2.04.messaging-and-notification.md

- 使用するプロジェクトの開き方の説明を修正
- ファイルパスをプロジェクト内のクラス名で指定するように修正

Fix document on how to open project and file path

---

AndroidStudio/answers/practice/fundamentals/1st/ScrollViewPractice/Practice1/app/src/main/res/menu/main.xml
AndroidStudio/assignments/fundamentals/6th/ListViewAssignment/src/main/res/menu/context_menu_main.xml
AndroidStudio/assignments/fundamentals/6th/ListViewAssignment/src/main/res/menu/main.xml
AndroidStudio/practice/advanced/1st/DebugPractice/src/main/res/menu/main.xml
AndroidStudio/practice/fundamentals/6th/ListViewPractice/src/main/res/menu/activity_main.xml

Fix lint android:showAsAction -> app:showAsAction

---

AndroidStudio/assignments/fundamentals/1st/LayoutAssignment/build.gradle
AndroidStudio/assignments/fundamentals/4th/MessagingAndNotification/app/build.gradle
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/build.gradle
AndroidStudio/practice/fundamentals/4th/MessagingAndNotification/app/build.gradle

build.gradleのdependenciesに残っていたcompileをimplementationに修正

Fix dependencies compile -> implementation

---

AndroidStudio/assignments/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/assignment/messagingandnotification/EditActivity.java
AndroidStudio/assignments/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/assignment/messagingandnotification/IntentActivity1.java
AndroidStudio/assignments/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/assignment/messagingandnotification/IntentActivity2.java
AndroidStudio/assignments/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/assignment/messagingandnotification/MainActivity.java
AndroidStudio/assignments/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/assignment/messagingandnotification/NotificationActivity1.java
AndroidStudio/assignments/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/assignment/messagingandnotification/NotificationActivity2.java
AndroidStudio/assignments/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/assignment/messagingandnotification/NotificationSubActivity1.java
AndroidStudio/assignments/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/assignment/messagingandnotification/NotificationSubActivity2.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/AnimationPracticeActivity.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/DrawablePracticeActivity.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/MainActivity.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/StringPractice1And2Activity.java
AndroidStudio/practice/fundamentals/3rd/ResourceManagement/app/src/main/java/jp/mixi/practice/resourcemanagement/StringPractice3Activity.java
AndroidStudio/practice/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/practice/messagingandnotification/IntentActivity1.java
AndroidStudio/practice/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/practice/messagingandnotification/IntentActivity2.java
AndroidStudio/practice/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/practice/messagingandnotification/MainActivity.java
AndroidStudio/practice/fundamentals/4th/MessagingAndNotification/app/src/main/java/jp/mixi/practice/messagingandnotification/NotificationActivity.java

fix #152
base class をAppCompatActivityにする

ActionBarActivity -> AppCompatActivity

---

AndroidStudio/build.gradle

change minSdkVersion

---

AndroidStudio/build.gradle

AndroidStudio 3.2のbuild toolで動作するように変更

upgrade to AndroidStudio 3.2

---

docs/introductions/1.05.how-to-build-for-gradle.md

変更点の修正前の状態で
```sh
$ ./gradlew -q relax
I'm home
I unlock the door
Relax...
```
となってしまっていて依存関係がおかしくなっていたので修正しました．

Androidのビルドについて(Gradle)のtaskの依存関係の修正
